### ISSUE TITLE
No module named 'sequana.pipelines_common

### ISSUE THREAD

**Issue by ejongepier** [sequana/multicov#1]
Hi!

I like to use sequana coverage but run into the following issue:

```
sequana_pipelines_coverage --help

Traceback (most recent call last):
  File "/path/to/envs/sequana/bin/sequana_pipelines_coverage", line 5, in <module>
    from sequana_pipelines.coverage.main import main
  File "/path/to/envs/sequana/lib/python3.7/site-packages/sequana_pipelines/coverage/main.py", line 6, in <module>
    from sequana.pipelines_common import *
ModuleNotFoundError: No module named 'sequana.pipelines_common'
```
For the installaton of sequana I followed [these recommendations](https://sequana.readthedocs.io/en/master/installation.html):

```
conda create -p /path/to/envs/sequana python=3.7.3
conda activate /path/to/envs/sequana
pip install sequana --upgrade
pip install sequana_coverage
```

Any pointers how to fix this would be much appreciated!

Thanks and best,
Evelien

**Comment by cokelaer** [comment]
sorry it took so long, but should be fixed by now.
